Repository TampereHacklab/mulysa, pull requests merged in 2020-12, with the labels that each got.

#282 Fix typo: asylum
  README.md
Labels: Minor, documentation

#284 Finnish
  api/locale/fi/LC_MESSAGES/django.po
  api/migrations/0006_auto_20201201_1558.py
  api/models.py
  emails/locale/fi/LC_MESSAGES/django.po
  users/locale/fi/LC_MESSAGES/django.po
  utils/locale/fi/LC_MESSAGES/django.po
  www/locale/fi/LC_MESSAGES/django.po
  www/templates/www/usersettings.html
Labels: enhancement, gui

#297 Feat/report userdata on api failed dooropen
  README.md
  api/tests.py
  api/views.py
Labels: enhancement
